/* GENERATED by scripts/icons-build.js — do not edit.
 * Source of truth is icons/material/*.svg and icons/custom/*.svg.
 * Run `npm run icons` after adding or changing one. */

/** Every icon is drawn on this grid. */
export const viewBox = "0 0 24 24";

/** Inner SVG markup for each icon, keyed by kebab-case name. */
export const icons = {
  "arrow-left": "<path d=\"m7.825 13 5.6 5.6 -1.425 1.4 -8 -8 8 -8 1.425 1.4 -5.6 5.6h12.175v2H7.825Z\"/>",
  "arrow-right": "<path d=\"M16.175 13H4v-2h12.175L10.575 5.4l1.425 -1.4 8 8 -8 8 -1.425 -1.4 5.6 -5.6Z\"/>",
  "search": "<path d=\"M19.6 21 13.3 14.7q-0.75 0.6 -1.725 0.95t-2.075 0.35q-2.725 0 -4.6125 -1.8875T3 9.5q0 -2.725 1.8875 -4.6125T9.5 3q2.725 0 4.6125 1.8875T16 9.5q0 1.1 -0.35 2.075t-0.95 1.725l6.3 6.3 -1.4 1.4ZM9.5 14q1.875 0 3.1875 -1.3125T14 9.5q0 -1.875 -1.3125 -3.1875T9.5 5q-1.875 0 -3.1875 1.3125T5 9.5q0 1.875 1.3125 3.1875T9.5 14Z\"/>",
};

export const iconNames = Object.keys(icons);

const escape = (s) => String(s).replace(/[&<>"]/g, (c) => `&#${c.charCodeAt(0)};`);

/**
 * Full <svg> markup for an icon, as a string — for plain HTML, Drupal
 * templates, or innerHTML. Decorative (aria-hidden) unless given a label.
 *
 *   iconSvg("search")                     // decorative, next to visible text
 *   iconSvg("search", { label: "Search" }) // icon-only, announced
 */
export function iconSvg(name, { label, className = "" } = {}) {
  const inner = icons[name];
  if (inner === undefined) throw new Error(`MSDS: no icon named "${name}"`);
  const a11y = label ? `role="img" aria-label="${escape(label)}"` : `aria-hidden="true"`;
  const cls = ["msds-icon", className].filter(Boolean).join(" ");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="currentColor" class="${escape(cls)}" ${a11y} focusable="false">${inner}</svg>`;
}
